### PR TITLE
Adding source API's for updating source address.

### PR DESCRIPTION
**Pull request by vamshi-k**
***Why:***
Giving an option for the application to add the source address instead of getting resolved underneath the kernel by providing API's to set the source address

Also, added API's for updating the hostname.

@sparrc Can you please review the change ?

### CODE REVIEW

**Comment by sparrc** [comment]
why have you added a field to the struct that doesn't get used anywhere?

**Comment by vamshi-k** [comment]
Can be used for debugging purposes too. There are situations where I wanted to know the hostname from which the packet stats are taken from.

**Comment by sparrc** [comment]
I'd prefer if you didn't add that, because it implies that the "Hostname()" function will look up the hosts actual name somehow

**Comment by vamshi-k** [comment]
@sparrc Any update on this ?

**Comment by sparrc** [comment]
> I'd prefer if you didn't add that, because it implies that the "Hostname()" function will look up the hosts actual name somehow

I was waiting for you to remove the [Set]Hostname() function.

**Comment by vamshi-k** [comment]
@sparrc I am have a list of hosts that I ping. List contains (hostname, ip of the host) and when I get a reply, I need to map host ip to host. Having this in a struct can give me more information about whom this pinger object refers to. If the Set/Get are to be removed, I can change the init function to add hostname as an argument (NewPinger) 

let me know if you something else that can make this work.

**Comment by vamshi-k** [comment]
@sparrc how about renaming it to PingerHostname() ?

**Comment by sparrc** [comment]
sorry vamshi-k but I won't be merging this. This could be easily solved in your own code by wrapping the struct and it's not the responsibility of a library to track metadata for you.

**Pull request closed without merging**
