### PR TITLE
Don't separate ping response header from received bytes

### PR DESCRIPTION
**Pull request by sparrc**
It's not clear to me that golang's ICMP parsing library actually requires separating the "payload" from the header of the response message. This removes ipv4Payload function entirely. Needs thorough testing before merging.

closes https://github.com/sparrc/go-ping/issues/61

### CODE REVIEW

**Comment by sparrc** [comment]
cc @AlirieGray @glinton 

As you were both in this code recently, can you please review?

**Comment by sparrc** [comment]
also cc @SuperQ

**Comment by SuperQ** [comment]
I guess I don't know the Go ICMP stuff well enough to give a good review. But, if it works, it works. :grin:

**Comment by glinton** [comment]
> It's not clear to me that golang's ICMP parsing library actually requires separating the "payload" from the header of the response message.

From what I can tell, it isn't required as it's handled in the [`ReadFrom` function](https://github.com/golang/net/blob/c98bf442cc908065c4df3decd0c6a9523c7896fa/ipv4/payload_cmsg.go#L40-L47)

**Comment by chn-lee-yumi** [comment]
Hello, this really fixed the bug, but I can't get this code using `go get`. Had it merged to master branch?

**Pull request merged**
