### PR TITLE
Check for IMCP ID

### PR DESCRIPTION
**Pull request by fastest963**
@sugy added a commit to check the icmp ID and verify the sequence number. This prevents other applications or pings from interfering with pinger

### CODE REVIEW

**Comment by sugy** [comment]
Thank you for making a pull request. But I have not written test code.

**Comment by fastest963** [comment]
@sugy I can write those if you want me to cherry-pick your commit into our fork?

**Comment by sugy** [comment]
@fastest963 Yes, thanks.

**Comment by ruschecker** [comment]
Found strange behaviour:
from time to time it is buggy.
1. Works pretty well on 5 nodes.
2. Work with flapping issues on 20 nodes:
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
5 packets transmitted, 5 packets received, 0% packet loss
6 packets transmitted, 5 packets received, 16.666666666666664% packet loss

3. Become crazy with 25 nodes
5 packets transmitted, 5 packets received, 0% packet loss
6 packets transmitted, 5 packets received, 16.666666666666664% packet loss
6 packets transmitted, 5 packets received, 16.666666666666664% packet loss
6 packets transmitted, 5 packets received, 16.666666666666664% packet loss
7 packets transmitted, 5 packets received, 28.57142857142857% packet loss
7 packets transmitted, 5 packets received, 28.57142857142857% packet loss
7 packets transmitted, 5 packets received, 28.57142857142857% packet loss
8 packets transmitted, 5 packets received, 37.5% packet loss
8 packets transmitted, 5 packets received, 37.5% packet loss
8 packets transmitted, 5 packets received, 37.5% packet loss
8 packets transmitted, 5 packets received, 37.5% packet loss
9 packets transmitted, 5 packets received, 44.44444444444444% packet loss
9 packets transmitted, 5 packets received, 44.44444444444444% packet loss
9 packets transmitted, 5 packets received, 44.44444444444444% packet loss
9 packets transmitted, 5 packets received, 44.44444444444444% packet loss
9 packets transmitted, 5 packets received, 44.44444444444444% packet loss
10 packets transmitted, 5 packets received, 50% packet loss
10 packets transmitted, 5 packets received, 50% packet loss
10 packets transmitted, 5 packets received, 50% packet loss
10 packets transmitted, 5 packets received, 50% packet loss
11 packets transmitted, 5 packets received, 54.54545454545454% packet loss
11 packets transmitted, 5 packets received, 54.54545454545454% packet loss
11 packets transmitted, 5 packets received, 54.54545454545454% packet loss
11 packets transmitted, 5 packets received, 54.54545454545454% packet loss

And using a lot of cpu

**Comment by sparrc** [comment]
Thank you for the contribution, but this change has already been merged in a separate PR, please let me know if you don't find the current implementation satisfactory.

**Pull request closed without merging**
